name: etesyncapp
summary: EteSync Tasks App
description: EteSync Tasks app
adopt-info: etesyncapp
icon: snap/gui/etesyncapp.png


confinement: strict
base: core22
grade: stable

slots:
 dbus-etesyncapp:
   interface: dbus
   bus: session
   name: com.ete_sync_app.ete_sync_app
    
apps:
  etesyncapp:
    command: etesyncapp
    common-id: com.ete_sync_app.ete_sync_app
    extensions: [ gnome ] # gnome includes the libraries required by flutter
    plugs:
    - network
    - home
    slots:
      - dbus-etesyncapp
parts:
  etesyncapp:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
    override-pull: |
      craftctl default
      THE_VERSION=$(cat version.txt)
      craftctl set version=${THE_VERSION}
    build-packages:
      - libsecret-1-dev
      #- libgpg-error-dev
      #- libjsoncpp25
      #- libjsoncpp-dev
    stage-packages:
      - libsecret-1-dev
      #- libgpg-error-dev
      #- libjsoncpp25
      #- libjsoncpp-dev
